### ISSUE TITLE
Printer.cfg

### ISSUE THREAD

**Issue by Sotiocsi** [Alex3DLabs/Klipper_Configs#1]
Hi.

You have done a very nice job.
I would like to do the same with a SKR-PRO base plate.

I get this error: "Unknown gcode_macro variable 'active_fan'"

Is it possible to get the finalized printer.cfg file from you?

Thanks, Soti.

**Comment by Alex3DLabs** [comment]
Thank you, I have too many other projects going on and have not had time to work on this one lately, but I will post the latest printer.cfg that I have working soon (hopefully tonight).  I worked past the active_fan issue, but not much further.

**Comment by Alex3DLabs** [comment]
Current printer.cfg and macro.cfg files updated.
